### ISSUE TITLE
关于节气时间误差问题

### ISSUE THREAD

**Issue by aLazyCoder** [cyanzhong/LunarCore#3]
大神你好，最近试用了你的这个日历算法，遇到个问题，2016年12月的生成数据中“大雪”这个节气是在12月6日，网上查到的标准时间是(12月7日的00:41)，而你上线的app中“大雪”这天也是12月7日！！！
请问，你在线上app中是如何修复这一误差的呢？

**Comment by cyanzhong** [comment]
@aLazyCoder 非常抱歉，这个问题在以前的线上版本里面也存在。我发现无论如何计算都会不准，所以最后还是抓取了数据内置了进去。不过这个库忘记更新了。现在你更新一下试试。

**Comment by aLazyCoder** [comment]
反应速度好快啊…


太感谢了！想要的就是这个！


谢谢谢谢了~~


原始邮件
发件人:Cyannotifications@github.com
收件人:cyanzhong/LunarCoreLunarCore@noreply.github.com
抄送:Leo Gaoglc123@163.com; Mentionmention@noreply.github.com
发送时间:2017年1月5日(周四) 17:17
主题:Re: [cyanzhong/LunarCore] 关于节气时间误差问题 (#3)


@aLazyCoder 非常抱歉，这个问题在以前的线上版本里面也存在。我发现无论如何计算都会不准，所以最后还是抓取了数据内置了进去。不过这个库忘记更新了。现在你更新一下试试。

**Comment by mxdios** [comment]
大神您好，返回的二十四节气好像有问题，显示的节气都延后了。比如2016年5月5日正确结果应该是立夏，但返回的是清明，2016年5月20日正确的是小满，返回的是谷雨，2016年6月5日是芒种，但返回是立夏。小历上显示正确

**Comment by cyanzhong** [comment]
我看了小历线上的版本似乎没有这个问题，给我点时间确认一下开源出来的版本是否一致。

**Comment by aLazyCoder** [comment]
我也收到到了问题推送了。。。新版算法内置的节气数据貌似没问题，只是节气数组顺序是从立春开始的，小寒和大寒这俩节气放到了最后。是这个引发的@mxdios的问题吧？

**Comment by mxdios** [comment]
是的，我把小寒大寒放到最后就没问题了，多谢大神指导。还有一个2016年12月31日是“休”，假日安排_worktime的@"y2016"里少了@"d1231":@2

**Comment by aLazyCoder** [comment]
😂我只是个路人甲，也是来学习的。。。这位@cyanzhong才是大神本人。。。

**Comment by cyanzhong** [comment]
确实是这么个事儿，之前更新的时候这一行漏掉了。

非常抱歉，现在好了。
